language: java
jdk: openjdk11
install: true
script:
  - mvn clean install -DskipTests=true
  - bash <(curl -s https://codecov.io/bash)
cache:
  directories:
  - $HOME/.m2
  - node_modules
after_success:
  - mvn clean test jacoco:report coveralls:report -DskipTests=true
after_failure:
  - cat target/surefire-reports/*.txt
