language: java
jdk: openjdk11
install: true
script: mvn clean install -DskipTests=true
cache:
  directories:
  - $HOME/.m2
  - node_modules
after_success:
  - mvn clean test jacoco:report coveralls:report
